version: 1.0.{build}
image: Visual Studio 2015
environment:
  matrix:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
matrix:
  fast_finish: false
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build_script:
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"celsomarques_shadowsocks-windows" /d:sonar.organization="celsomarques-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="cc66ac52dd2c887639e58c43a749585a0a3683c5"
 - msbuild /verbosity:quiet "shadowsocks-windows.sln"
 - SonarScanner.MSBuild.exe end /d:sonar.login="cc66ac52dd2c887639e58c43a749585a0a3683c5"
artifacts:
- path: shadowsocks-csharp\bin\x86\Release\Shadowsocks.exe
  name: Shadowsocks-release.exe
- path: shadowsocks-csharp\bin\x86\Debug\Shadowsocks.exe
  name: Shadowsocks-debug.exe
